### ISSUE TITLE
OutputCache

### ISSUE THREAD

**Issue by mgroves** [brantburnett/Couchbase.Extensions#8]
Is there a way to use OutputCache with the caching extension? Is OutputCache even in ASP.NET Core? With ASP.NET MVC, you could put attributes on controller action methods, and the result would be cached (in-proc by default).

**Comment by jeffrymorris** [comment]
Mr. Groves -

Yes, there is an output cache in core:
https://docs.microsoft.com/en-us/aspnet/core/performance/caching/response

I haven't used it yet, but assume it would use whatever Distributed Cache
you have configured.

-Jeff

On Wed, Aug 30, 2017 at 1:10 PM, Matthew D. Groves <notifications@github.com

**Comment by mgroves** [comment]
That's the ResponseCache, which I believe just affects the HTTP headers, it doesn't actually store in cache. It might be the case that OutputCache was not created for ASP.NET Core; I can't find evidence to suggest otherwise.

**Comment by brantburnett** [comment]
@mgroves 

I think you use it in combination with the [Response Caching Middleware](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/middleware?tabs=aspnetcore2x).  This sees the headers coming back from MVC and then performs caching based on the headers at the server side.

**Comment by mgroves** [comment]
I followed the below steps according to that link, and ResponseCache doesn't seem to be putting anything in Couchbase. It's not clear to me if I'm doing something wrong or it's a bug.

1. Added MicrosoftAspNetCore.ResponseCaching (v1.1.2)
2. In Startup.cs, I added `services.AddResponseCaching();` to `ConfigureServices`
3. In Startup.cs, I added `app.UseResponseCaching();` to `Configure`
4. I added `[ResponseCache(Duration = 10)]` attribute to an action in `HomeController`

When I go to the HomeController action, the page loads and displays correctly, but nothing is cached into Couchbase.

I should also note that, otherwise, caching is working fine. I'm using `IDistributedCache` methods like `GetString`, `SetString`, `Set<>` and so on, and values set with those methods are showing up in Couchbase correctly.

**Comment by brantburnett** [comment]
@mgroves 

Looking at the code for response caching in .NET Core, it appears that in-memory caching is the only option.

https://github.com/aspnet/ResponseCaching/blob/dev/src/Microsoft.AspNetCore.ResponseCaching/ResponseCachingMiddleware.cs#L40

It also doesn't appear to have an extension point to substitute other behavior, unless we replicate the very large amount of functionality in ResponseCacheMiddleware.  I think serializing CachedResponse would probably be a bit tricky, too.

Brant

**Comment by mgroves** [comment]
I could create an ActionFilter pull request, would that be something you'd want in this project?

**Comment by brantburnett** [comment]
@mgroves 

My concern would be getting something like that right.  There's a whole lot of complexity around what to cache and when, and how to vary it by headers and query params, caching redirects, etc.  That logic is already worked out in the ResponseCaching library of .NET Core, and replicating it correctly seems like it would be difficult and buggy.

Perhaps we should instead try to get ResponseCaching to add support for substituting an IDistributedCache?  Maybe file an issue or pull on that project?

**Comment by mgroves** [comment]
Okay, just submitted an issue there - https://github.com/aspnet/ResponseCaching/issues/137
